Repository pycontribs/mk, pull requests merged in 2024-01, with the labels that each got.

#172 Remove obsolete RTD config option
  .readthedocs.yml
Labels: skip-changelog

#173 Fix integration pipeline
  .config/requirements.in
  playbooks/test-integration.yml
  samples/integration/ansible-lint.txt
  samples/integration/cookiecutter.txt
  samples/integration/podman.txt
  samples/integration/typeshed.txt
Labels: skip-changelog

#169 Recognize more possible taskfile config filenames
  src/mk/tools/taskfile.py
Labels: bug

#167 Add nox tool support
  .config/requirements.in
  playbooks/test-integration.yml
  pyproject.toml
  samples/integration/nox.txt
  src/mk/tools/nox.py
  tox.ini
Labels: enhancement

#176 Support py312
  .config/requirements.txt
  .github/workflows/tox.yml
  pyproject.toml
  tox.ini
Labels: bug

#177 Drop support for py38
  .config/requirements.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  mypy.ini
  pyproject.toml
  tox.ini
Labels: enhancement

#178 Update linters
  .pre-commit-config.yaml
  src/mk/ctx.py
  src/mk/text.py
  src/mk/tools/git.py
  test/test_cli.py
Labels: bug

#179 Group dependabot lockfile updates
  .github/dependabot.yml
Labels: skip-changelog

#183 Update test dependencies
  .config/constraints.txt
  .config/requirements.in
  .config/requirements.txt
  pyproject.toml
  tox.ini
Labels: skip-changelog

#184 Clean up unused and transitive dependencies. Remove impoortlib-metadata.
  .config/constraints.txt
  .config/requirements.txt
  src/mk/__init__.py
Labels: enhancement

#185 Clean up tox `deps` env
  .config/constraints.txt
  tox.ini
Labels: skip-changelog
